AWSTemplateFormatVersion: 2010-09-09
Resources:
  BlogS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: blog-app
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        ErrorDocument: index.html
        IndexDocument: index.html

  BlogS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref BlogS3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
            - s3:GetObject
            Effect: Allow
            Resource: !Sub 
              - 'arn:aws:s3:::${BucketName}/*'
              - BucketName: !Ref BlogS3Bucket
            Principal: '*'

  BlogCloudFrontCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties: 
      CachePolicyConfig: 
        DefaultTTL: 300 # 86400
        MaxTTL: 300 # 31536000
        MinTTL: 300
        Name: blog-app-cache-policy
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig: 
            CookieBehavior: none
          EnableAcceptEncodingBrotli: false
          EnableAcceptEncodingGzip: false
          HeadersConfig: 
            HeaderBehavior: none
          QueryStringsConfig: 
            QueryStringBehavior: none

  BlogCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties: 
      DistributionConfig:
        Aliases:
          - blog.nikkiyodo.com
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        DefaultCacheBehavior:
          CachePolicyId: !Ref BlogCloudFrontCachePolicy
          TargetOriginId: !Ref BlogS3Bucket
          ViewerProtocolPolicy: redirect-to-https
        Enabled: true
        Origins:
          - CustomOriginConfig:
              OriginProtocolPolicy: http-only
            DomainName: !Sub
              - '${BucketName}.s3-website.${AWS::Region}.amazonaws.com'
              - BucketName: !Ref BlogS3Bucket
            Id: !Ref BlogS3Bucket
            # OriginAccessControlId: !Ref BlogOAC
        ViewerCertificate: 
          AcmCertificateArn: !Ref BlogCertificate
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only

  BlogCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: blog.nikkiyodo.com
      ValidationMethod: DNS
 
  BlogRecordSet:
    Type: AWS::Route53::RecordSet
    Properties: 
      AliasTarget: 
        DNSName: !GetAtt BlogCloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
      HostedZoneId: !ImportValue BlogHostedZoneId
      Name: blog.nikkiyodo.com
      Type: A
  